# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the website.
[en]
  languageCode = "en-us"

